### PR TITLE
feat(vertical-pod-autoscaler): add topologySpreadConstraints for admi…

### PR DESCRIPTION
**Pull request by starlightromero**
…ssions-controller, recommender, and updater

### CODE REVIEW

**Comment by sebastien-prudhomme** [comment]
Hi @starlightromero, no way for you to configure it on the cluster level?

**Comment by starlightromero** [comment]
`topologySpreadConstraints` are specifically in the pod spec. Short of using a policy controller like [Gatekeeper](https://github.com/open-policy-agent/gatekeeper) in order to mutate all pods on a cluster, the `topologySpreadConstraints` attribute must be applied to each pod.

**Comment by sebastien-prudhomme** [comment]
@starlightromero I mean this: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints

**Comment by starlightromero** [comment]
@sebastien-prudhomme Thanks for clarifying. There is a way to configure it at the cluster level. Does that prohibit this change from being useful?

**Comment by starlightromero** [comment]
Hi @sebastien-prudhomme. I'm coming back to this PR. Thank you for the reply. I have updated the PR accordingly.

**Pull request merged**
