### PR TITLE
Add option to disable components

### PR DESCRIPTION
**Pull request by robinelfrink**
This PR adds options to disable specific VPA-components:

```
admissionController:
  enable: true
...
updater:
  enable: true
```

### CODE REVIEW

**Comment by robinelfrink** [comment]
Ah, I hadn't read "I'm not accepting any pull requests"...

Please feel free to cut & paste changes in this PR without any recognition :)

**Comment by sebastien-prudhomme** [comment]
Hi @robinelfrink, it should be OK for the PR :-)

Two things:

- rename the field `enabled` as this is more commonly used by chart authors
- I'm not sure that disabling recommender is a good idea as other components needs it: what is your use case?

**Comment by robinelfrink** [comment]
Crap, I just changed everything from `enabled` to `enable` :) I'll change them back to `enable`.

It never occured to me that the recommender is always needed; actually it's the only one I'm interested in.

I'll add two commits right away, to be squashed later.

**Comment by robinelfrink** [comment]
Commits squashed.

**Comment by sebastien-prudhomme** [comment]
@robinelfrink You also need to bump the version, as this is a new feature change it to `3.6.0`.

**Comment by sebastien-prudhomme** [comment]
@robinelfrink The field is now `enable` again after you squash the commits

**Comment by robinelfrink** [comment]
Oh, crap. It must be a monday. Please tell me it's a monday.

**Pull request merged**
